import { V2_CONFIG } from "../config.js";
import { GROUND_DEFAULT_PARAMS } from "../../core/legacy/chunkGroundTsl.js";
import { MEADOW_DEFAULT_PARAMS } from "../../core/legacy/chunkMeadowTsl.js";

function deepCloneJson(x) {
  return JSON.parse(JSON.stringify(x));
}

export function createToolState() {
  return {
    /** `view` (orbit only) | `sculpt` | `paint` | `treePaint` | `spline` | `decals` | … Defaults to `view` — matches v1. */
    mode: "view",
    /**
     * Shared gizmo (TransformControls) settings — applies to every mode that
     * uses the gizmo: cliffs, props, actors, water, waterfall, decals, and
     * road decals. `space` = "world" (rings aligned to world axes — best for
     * cardinal alignment) or "local" (rings aligned to the object's own axes
     * — best for incremental tweaks on already-rotated objects). Toggle in
     * any gizmo mode with the **Q** hotkey. `rotationSnapDeg` is the snap
     * angle (degrees) applied while holding **Shift** during a rotate drag;
     * 0 disables snap. Scale gizmo always uses local space (three.js fixed).
     */
    gizmo: {
      space: "world",
      rotationSnapDeg: 15,
    },
    /** `tile` = grid material; `tsl` = procedural TSL; `image` = tiled image-slot material. */
    terrainSurface: "tile",
    /** Default tile-grid ground appearance (the `tile` surface). Defaults match
     *  the previously-hardcoded createSharedTileMaterial() values so existing
     *  scenes are unchanged; the editor exposes these as live controls. */
    groundTile: {
      textureScale: 400,
      gradientIntensity: 0.5,
      gradientBias: 0.0,
      tileColor: "#e6e3e3",
      gridColor: "#444444",
      gridLineColor: "#111111",
    },
    /** Texture-library slot ids picked by the surface modes that use slots. */
    textureSlots: {
      cliffSlotId: "cliff_rock",
      groundSlotId: "grass_005",
    },
    /**
     * Paint mode — 4 layers (layer 0 is base, layers 1..3 are R/G/B splat channels).
     * `activeLayer` selects what the brush paints (0 = eraser → pulls toward base).
     */
    paint: {
      activeLayer: V2_CONFIG.paint.defaultActiveLayer,
      layerSlotIds: [
        "ground_037",
        "cobblestone",
        "cliff_rock",
        "grass_005",
        "ground_037",
        "cobblestone",
        "cliff_rock",
      ],
      noiseMask: 0,
      noiseScale: 3.0,
      noiseOctaves: 3,
      noiseEdgeOnly: false,
      maskPreset: "none",
      maskRotation: 0,
      maskRandomRotation: false,
      maskFollowStroke: false,
      soloLayer: -1,
      heightBlend: 0,
      heightContrast: 0.5,
    },
    groundTsl: deepCloneJson(GROUND_DEFAULT_PARAMS),
    meadowTsl: deepCloneJson(MEADOW_DEFAULT_PARAMS),
    tslGroundUi: {
      groundPresetKey: "default",
      meadowPresetKey: "default",
      meadowMix: 0.55,
      meadowSlopeMin: 0.45,
      meadowSlopeMax: 0.92,
    },
    sculptMode: "raiseLower",
    /**
     * v1 `sculptBrush` for raise/lower: `smooth` (uses brushFalloff enum) | `plateau` (mesa) | `crater` (rim-pit).
     * FBM peak / noise / terrace / ramp / erosion are separate modes via `sculptMode`.
     */
    raiseLowerStamp: V2_CONFIG.sculpt.defaultRaiseLowerStamp,
    brush: {
      radius: V2_CONFIG.sculpt.defaultRadius,
      strength: V2_CONFIG.sculpt.defaultStrength,
      falloff: V2_CONFIG.sculpt.defaultFalloff,
      /** Only affects raise/lower `smooth` stamp — v1 `PARAMS.brushFalloff`. */
      brushFalloff: V2_CONFIG.sculpt.defaultBrushFalloff,
      spacingFactor: V2_CONFIG.sculpt.spacingFactor,
      previewShape: V2_CONFIG.sculpt.previewShape,
    },
    noiseBrush: {
      noiseScale: V2_CONFIG.sculpt.noiseScale,
      noiseOctaves: V2_CONFIG.sculpt.noiseOctaves,
    },
    /**
     * Sculpt brush mask — PNG stamp that modulates stamp-mode deltas
     * (raiseLower, noise, fbmPeak, terrace). Mirror of `paint.mask*` fields but
     * independent so paint and sculpt can run different stamps simultaneously.
     */
    sculptMask: {
      preset: "none",
      rotation: 0,
      randomRotation: false,
      followStroke: false,
    },
    terrace: { ...V2_CONFIG.sculpt.terrace },
    ramp: { ...V2_CONFIG.sculpt.ramp },
    erosion: { ...V2_CONFIG.sculpt.erosion },
    fbmPeak: { ...V2_CONFIG.sculpt.fbmPeak },
    gen: { ...V2_CONFIG.sculpt.gen },
    borderMountains: { ...V2_CONFIG.borderMountains },
    terrain: {
      lodEnabled: true,
      activeRadiusInChunks: V2_CONFIG.lod.activeRadiusInChunks,
    },
    autoCliffEnabled: true,
    autoCliff: {
      slopeStart: 0.6,
      slopeEnd: 0.7,
      rockScale: 0.01,
      rockBrightness: 2.0,
      rockContrast: 1.1,
      rockTint: "#ffffff",
      rockNormalStr: 1.0,
      rockBlendSharp: 1.0,
      rockRoughMul: 1.5,
      triplanarSharp: 4.0,
    },
    // exposure overridden to 1.0 here so a fresh boot (default skyMode below is
    // "procedural") starts at the procedural exposure — the init path applies the
    // sky mode without a prev→next swap, so it won't pull from skyExposureByMode.
    light: { ...V2_CONFIG.light, exposure: 1.0 },
    skyMode: "procedural",
    /** Tone-mapping exposure remembered per sky mode (applied on mode switch). */
    skyExposureByMode: {
      physical: 0.5,
      procedural: 1.0,
      hdr: 0.5,
    },
    physicalSky: { ...V2_CONFIG.physicalSky },
    /** `skyMode === "procedural"` — daynight-sky dome params (see config.js). */
    proceduralSky: { ...V2_CONFIG.proceduralSky },
    /** Volumetric cloud deck for the procedural sky (daynight-sky port). */
    volumetricCloudDayNight: { ...V2_CONFIG.volumetricCloudDayNight },
    /** Cloud shadows for the daynight volumetric deck (terrain + ocean). */
    cloudShadows: { ...V2_CONFIG.cloudShadows },
    /** God-rays / light shafts for the daynight volumetric deck. */
    cloudGodRays: { ...V2_CONFIG.cloudGodRays },
    /** Cloud bloom for the daynight volumetric deck (final-frame bloom). */
    cloudBloom: { ...V2_CONFIG.cloudBloom },
    lensFlare: { ...V2_CONFIG.lensFlare },
    /**
     * Post-processing master switch + per-effect params.
     * When `enabled === false` the renderer falls back to a direct
     * `renderer.render(scene, camera)` (zero post-FX cost).
     * Bloom uses Three's TSL `BloomNode`; defaults match folio-2025 with a
     * touch more punch (lower threshold, slightly higher strength).
     */
    postFx: {
      enabled: false,
      bloom: {
        enabled: true,
        strength: 0.3,
        threshold: 0.9,
        radius: 0.4,
        smoothWidth: 1.0,
      },
      /**
       * FXAA replaces the renderer's MSAA, which doesn't apply once we render
       * through `RenderPipeline`. On by default whenever post-FX is enabled.
       */
      fxaa: {
        enabled: true,
      },
      /**
       * Screen-Space Ambient Occlusion via `n8ao-webgpu` (TSL port of N8AO).
       * Off by default — first enable lazily allocates the N8AO node, which
       * costs a one-time ~50–200 ms shader compile.
       *
       * Quality presets adjust `aoSamples` / `denoiseSamples` / `denoiseRadius`
       * — changing them rebuilds shaders, so do it once at startup.
       *
       * `transparencyAware` is gated separately (off by default) because it
       * costs ~2 extra full-scene renders per frame for transparent depth.
       *
       * `aoRadius` is in world units when `screenSpaceRadius` is false (the
       * default), otherwise in pixels.
       */
      ssao: {
        enabled: false,
        quality: "Medium",
        aoRadius: 5,
        distanceFalloff: 1,
        intensity: 3,
        color: "#000000",
        halfRes: false,
        depthAwareUpsampling: true,
        screenSpaceRadius: false,
        displayMode: "Combined",
        transparencyAware: false,
      },
      /**
       * "Color & Polish" bundle — single fullscreen pass that applies color
       * grading + vignette + film grain on top of the final image. Off by
       * default (master `enabled` false) so the polish pass is skipped from
       * the graph entirely until the user opts in. Once enabled, leaving any
       * sub-slider at its identity value (brightness 0, contrast 1,
       * saturation 1, vignetteStrength 0, grainStrength 0, etc.) costs a
       * few extra muls per pixel — effectively free.
       */
      polish: {
        enabled: false,
        brightness: 0,
        contrast: 1,
        saturation: 1,
        /** -1 (cool/blue) to 1 (warm/orange). */
        temperature: 0,
        /** -1 (green) to 1 (magenta). */
        tint: 0,
        /** 0..1. 0 = no vignette. */
        vignetteStrength: 0,
        /** Inner edge of falloff. 0 = darken from screen center, 1 = corners only. */
        vignetteFalloff: 0.5,
        /** 0 = circular, 1 = square (more elongated on widescreen). Reserved for now. */
        vignetteRoundness: 1,
        vignetteColor: "#000000",
        /** 0..0.3 typical. 0 = no grain. */
        grainStrength: 0,
        /** Higher = finer grain. 1 = ~screen-pixel-sized. */
        grainSize: 1,
      },
      /**
       * RCAS contrast-adaptive sharpening (FidelityFX). Sits AFTER FXAA so it
       * counteracts the softening that FXAA introduces. Off by default.
       */
      sharpen: {
        enabled: false,
        /** User slider 0..1 (low → high). Internally remapped to addon param. */
        sharpness: 0.5,
        /** Attenuate sharpening in noisy areas. Off by default. */
        denoise: false,
      },
      /**
       * Lens-style chromatic aberration. Off by default — at low strengths
       * gives a subtle "real lens" feel, at high strengths a stylized look.
       */
      chromaticAberration: {
        enabled: false,
        /** Aberration magnitude. 0 = none, ~1 = lens-like, >2 = stylized. */
        strength: 1,
        /** Per-channel scale separation. ~1.1 default from the addon. */
        scale: 1.1,
      },
      /**
       * Depth of Field (Bokeh — three.js TSL DepthOfFieldNode). Heavy:
       * allocates 6 internal RTs and runs CoC + 64-tap + 16-tap blurs in
       * half-res once enabled. Off by default.
       *
       * `focusDistance` and `focalLength` are in WORLD UNITS — match them to
       * your scene scale. With the editor's typical camera at ~150 units and
       * max distance 1500, `focusDistance: 50, focalLength: 30` gives a
       * sensible mid-scene focus.
       */
      dof: {
        enabled: false,
        focusDistance: 50,
        focalLength: 30,
        /** Artistic blur size. 0 = none, ~5 = subtle, ~15 = strong. */
        bokehScale: 5,
      },
    },
    csm: { ...V2_CONFIG.csm },
    fog: {
      height: { ...V2_CONFIG.fog.height },
      distance: { ...V2_CONFIG.fog.distance },
    },
    interior: { ...V2_CONFIG.interior, manualBoxes: [] },
    volumetricCloud: {
      ...V2_CONFIG.volumetricCloud,
      seed: Math.random() * 1000,
    },
    volumetricCloudOptimized: {
      ...V2_CONFIG.volumetricCloudOptimized,
      seed: Math.random() * 1000,
    },
    volumetricCloudV3: {
      ...V2_CONFIG.volumetricCloudV3,
      seed: Math.random() * 1000,
    },
    playSmoke: {
      enabled: true,
      emitRate: 48,
      trigger: 0.04,
      opacity: 0.55,
      sizeMin: 0.55,
      sizeMax: 1.05,
      sizeGrowth: 2.6,
      lifeMin: 0.65,
      lifeMax: 1.45,
      rise: 0.75,
      spread: 0.55,
      drag: 0.12,
      color: "#6a6c76",
    },
    playCar: {
      accelScale: 1.0,
      maxSpeedScale: 1.0,
      speedometerScale: 1.0,
      cameraDistance: 10,
      cameraHeight: 3.5,
      cameraChaseSpeed: 3.5,
      cameraDriftLag: 1.8,
    },
    /**
     * Play-mode camera collision (chase cam wall pull-in + floor lift).
     * `enabled` master switch; `wallPullEnabled` and `floorClampEnabled` toggle
     * the two passes independently. `offset` = skin distance from cliff/terrain
     * surfaces. `easeOut` = exponential rate (per second) at which the wall
     * pull-in relaxes back out once the obstacle is gone.
     */
    playCamera: {
      enabled: false,
      wallPullEnabled: true,
      floorClampEnabled: true,
      offset: 0.3,
      easeOut: 5,
    },
    /** Car Howler layers (vehicle bus). Assets: `v2/static/sounds/vehicle/` */
    playCarAudio: {
      enabled: false,
      /** Overall gain on synth engine loop (`joao_janz__synth-car-engine-loop.wav`) */
      engineMul: 1,
      /** 0 = auto pitch ref from car max speed (~45 m/s); else full rev at this m/s */
      engineRefTopSpeed: 0,
      engineVol: 1,
      engineVolAtTop: 1,
      enginePitchMin: 1,
      enginePitchMax: 2.85,
      enginePitchBoostMax: 3.55,
      enginePitchIdleSpeedMax: 0.35,
      enginePitchCurvePow: 1,
      enginePitchEase: 10,
      /** Legacy — coast gate removed; engine always on in car */
      engineCoastSpeedMin: 0.6,
      engineFadeEaseUp: 18,
      engineCoastFadeEaseLo: 2.6,
      engineCoastFadeEaseHi: 0.4,
      windMul: 0,
      nitroMul: 0.3,
      wheelsMul: 0,
      /** Handbrake (Space) drift / brake loop gain */
      driftBrakeMul: 0.45,
      /** Howler sprite loop window (ms). Duration 0 = loop whole file. Rebuild car audio to apply. */
      engineLoopStartMs: 0,
      engineLoopDurationMs: 0,
      windLoopStartMs: 0,
      windLoopDurationMs: 0,
      wheelsLoopStartMs: 0,
      wheelsLoopDurationMs: 0,
      driftBrakeLoopStartMs: 0,
      driftBrakeLoopDurationMs: 0,
    },
    /**
     * Runtime mixer (Howler) — Unity-style buses: master × category.
     * Persisted in project JSON via terrainSerializer.
     */
    audio: {
      muteAll: false,
      pauseWhenHidden: true,
      buses: {
        master: { volume: 1, mute: false },
        sfx: { volume: 1, mute: false },
        music: { volume: 0.85, mute: false },
        voice: { volume: 1, mute: false },
        ui: { volume: 1, mute: false },
        vehicle: { volume: 1, mute: false },
      },
    },
    playSpawn: {
      enabled: true,
      x: 0,
      y: 0,
      z: 0,
      yawDeg: 0,
    },
    treePaint: {
      activeSlot: 0,
      density: 0.5,
      minSpacing: 4,
      scaleMin: 0.8,
      scaleMax: 1.2,
      randomRotation: true,
      massPlaceCount: 1000,
      massPlaceKeepExisting: true,
      slopeEnabled: true,
      slopeMax: 0.7,
    },
    treeLod: {
      lod0Distance: 120,
      lod1Distance: 300,
      fadeOutDistance: 600,
      castShadow: true,
    },
    /** 3-tier LOD for tree leaf cards (FoliageLodRenderer + treeStore). */
    foliageLod: {
      lod0Distance: 80,
      lod1Distance: 200,
      fadeOutDistance: 600,
    },
    /** Geometry LOD + hide distance for painted billboards (BillboardRenderer). */
    billboardFoliageLod: {
      lod0Distance: 80,
      lod1Distance: 200,
      fadeOutDistance: 600,
    },
    foliagePaint: {
      activeSlot: 0,
      density: 0.8,
      minSpacing: 1.5,
      scaleMin: 0.7,
      scaleMax: 1.3,
      randomRotation: true,
      /** Skip scatter on steep terrain (same test as tree paint). */
      slopeEnabled: true,
      slopeMax: 0.7,
      massPlaceCount: 1000,
      massPlaceKeepExisting: true,
      /** LMB erases instead of paints (Alt/Shift also erase). */
      erase: false,
      /** When erasing: remove all slots in brush; default = active slot only. */
      eraseAllSlots: false,
    },
    /** Procedural billboard ground cover (separate from foliage paint + GPU grass). */
    billboardGrassPaint: {
      activeSlot: 0,
      density: 1.5,
      minSpacing: 0.9,
      scaleMin: 0.7,
      scaleMax: 1.3,
      randomRotation: true,
      slopeEnabled: true,
      slopeMax: 0.7,
      massPlaceCount: 30000,
      massPlaceKeepExisting: true,
      erase: false,
      eraseAllSlots: false,
    },
    billboardGrassLod: {
      /** Paint spacing grid (render uses terrain chunks, not this size). */
      patchSize: 16,
      lodHysteresis: 2,
      lod0Distance: 50,
      lod1Distance: 120,
      fadeOutDistance: 280,
      /** Shrinks draw distance when camera is high (orbit / flight). */
      aerialFadeStrength: 1.4,
    },
    billboardGrassSlots: ["meadow", "dry", "moss", "wheat"].map((preset, i) => {
      const palettes = {
        meadow: {
          colorBottom: "#1a4d12",
          colorMid: "#3d8f2a",
          colorTop: "#6bc44a",
          name: "Meadow",
        },
        dry: {
          colorBottom: "#4a3d1a",
          colorMid: "#8f7a3d",
          colorTop: "#c4a85a",
          name: "Dry field",
        },
        moss: {
          colorBottom: "#142e18",
          colorMid: "#2a5234",
          colorTop: "#4a8f55",
          name: "Moss",
        },
        wheat: {
          colorBottom: "#5a4a18",
          colorMid: "#9a7a28",
          colorTop: "#d4b850",
          name: "Wheat",
        },
      };
      const p = palettes[preset];
      return {
        name: p.name,
        enabled: true,
        preset,
        baseScale: 1.0,
        planeCount: 3,
        planeSpread: "full",
        tilt: 0.28,
        tiltMode: "stable",
        structureSeed: 42069 + i * 1000,
        width: 1.8,
        height: 2.0,
        colorBottom: p.colorBottom,
        colorMid: p.colorMid,
        colorTop: p.colorTop,
        noiseScale: 4,
        noiseStrength: 0.35,
        windScrollSpeed: 0.08,
        windScrollScale: 2,
        windShadeStrength: 0.42,
        swaySpeed: 1.6,
        swayStrength: 0.07,
        groundOcclusion: 0.78,
        normalUpBias: 0.94,
        textureUrl: "textures/billboardGrass/grassmask1.jpg",
        maskInAlpha: 0,
        alphaTest: 0.32,
        roughness: 0.92,
      };
    }),
    foliageSlots: [0, 1, 2, 3, 4, 5, 6, 7].map((i) => ({
      name: `Slot ${i + 1}`,
      enabled: true,
      textureUrl: null,
      baseScale: 1.0,
      planeCount: 3,
      planeSpread: "full",
      tilt: 0.28,
      tiltMode: "stable",
      structureSeed: 42069 + i * 1000,
      width: 1.8,
      height: 2.0,
      alphaTest: 0.5,
      roughness: 0.85,
      colorTint: "#ffffff",
      groundOcclusion: 0.7,
      normalBending: 0.6,
      sssIntensity: 1.5,
      swaySpeed: 0,
      swayStrength: 0.12,
    })),
    treeSlots: [0, 1, 2, 3, 4, 5, 6, 7].map((i) => ({
      name: `Slot ${i + 1}`,
      enabled: true,
      presetFile: null,
      baseScale: 1.0,
      foliage: {
        bottomColor: "#2d5a1b",
        topColor: "#5aaa2a",
        colorVar: 0.12,
        treeColorVar: 0.15,
        alphaCutoff: 0.45,
        normalBias: 1.0,
        leafWarp: 0.28,
        aoStr: 0.7,
        sssStr: 0.0,
        sssPow: 2.0,
        sssColor: "#c8e070",
        rimStr: 0.07,
        rimPow: 2.5,
        rimColor: "#c8ffaa",
        windSpeed: 0.9,
        windStr: 0.0,
        windMicro: 0.0,
      },
    })),
    cliffs: {
      activeSlot: 0,
      sinkOffset: 2,
      transformMode: "translate",
      blendSlopeLow: 0.5,
      blendSlopeHigh: 0.85,
      blendNoiseScale: 0.06,
      blendNoiseStr: 0.15,
      blendGroundScale: 1.0,
      blendGroundOffsetX: 0.0,
      blendGroundOffsetZ: 0.0,
      blendRockScale: 0.01,
      blendRockBrightness: 2.0,
      blendRockContrast: 1.1,
      blendTriplanarSharp: 4.0,
    },
    /** Cliff-blend paint mask brush (world XZ override onto placed cliff GLBs). */
    cliffPaint: {
      erase: false,
    },
    cliffSlots: [
      { name: "Cliff 1", loaded: false },
      { name: "Cliff 2", loaded: false },
      { name: "Cliff 3", loaded: false },
      { name: "Cliff 4", loaded: false },
      { name: "Cliff 5", loaded: false },
    ],
    props: {
      activeSlot: 0,
      sinkOffset: 0,
      transformMode: "translate",
      placementMode: "place",
      density: 0.5,
      minSpacing: 3,
      scaleMin: 0.8,
      scaleMax: 1.2,
      randomRotation: true,
    },
    propLod: {
      lod0Distance: 80,
      lod1Distance: 200,
      fadeOutDistance: 500,
      castShadow: true,
    },
    propSlots: [],
    barrier: {
      erase: false,
      showOverlay: true,
      overlayOpacity: 0.35,
    },
    hole: {
      erase: false,
      showOverlay: true,
      overlayOpacity: 0.35,
    },
    cave: {
      // Box-room placeholder sizes. Tuned so a default cave fits comfortably
      // under a brush radius ~8 hole and gives the player room to land + walk.
      width: 12,
      depth: 12,
      height: 6,
      opening: 4,
      ceilingOffset: 0.5,
    },
    /**
     * Tunnel mode — composite tool: click points on terrain (entrance face →
     * exit face), Create builds the tube AND stages both mouths: approach
     * trench carved into the terrain, terrain "membrane" hole-punched out of
     * the tube interior, BVH rebaked. Tube floor sits `mouthLift` above the
     * clicked points.
     */
    tunnel: {
      radius: 6,
      mouthLift: 0.2,
      /** How far the tube extends out of the face past the clicked point (m). */
      mouthExtend: 6,
      /** Trench carve distance along the curve inward from each tube end (m). */
      carveLength: 12,
      /** Trench half-width = radius × this. */
      trenchWidthFactor: 1.15,
      /** Trench floor below the tube floor (m). */
      trenchDepth: 0.4,
      /** Vertical slack for the membrane hole band (m). */
      membraneMargin: 0.9,
      radialSegs: 24,
      pathSegs: 220,
      color: "#6c727a",
      outerColor: "#cc2222",
      innerColor: "#2a2a32",
      /** Extra hole radius beyond tube R at each mouth disc (m). */
      mouthPortalMargin: 1.25,
    },
    ambientFx: {
      erase: false,
      effectType: "butterflies",
      emitterRadius: 12,
      density: 3,
      flapSpeed: 8.0,
      flapAngle: 0.8,
      glideRatio: 0.45,
      showRings: true,
      windX: 1.0,
      windZ: 0.3,
      windStrength: 1.0,
      leafSpawnHeight: 20,
      leafSize: 0.25,
      leafGravity: 0.002,
      leafTerminalVelocity: 0.02,
      leafRotationSpeed: 0.0015,
      leafAirResistance: 0.99,
      leafWindInfluence: 1.0,
      leafOpacity: 0.85,
      leafScale: 1.0,
      leafFloorOffset: 1.5,
      leafActiveType: 0,
      leafTint0: "#ff6b35",
      leafTint1: "#8B4513",
      leafTint2: "#2d7a2d",
      leafTex0: "",
      leafTex1: "",
      leafTex2: "",
    },
    fleur: {
      erase: false,
      activeSlot: 0,
      subMode: "ground",
      bloomShape: 0,
      perStroke: 20,
      minSpacing: 0.4,
      scaleMin: 0.4,
      scaleMax: 0.7,
      hoverBase: 0.45,
      hoverVariance: 0.1,
      stemBase: "#1f5c32",
      stemTop: "#6bae6e",
      stemStaticCurve: 0.1,
      interactRadius: 1.5,
      interactStrength: 0.4,
      interactGain: 0.85,
      windAmp: 0.042,
      windSpeed: 1.12,
      colorA: {
        preset: "main",
        inner: "#fff4b8",
        outer: "#fb8da0",
        glow: 0.28,
      },
      colorB: {
        preset: "sakura",
        inner: "#ffd9ea",
        outer: "#ff7ab2",
        glow: 0.32,
      },
    },
    water: {
      scale: 0.3,
      cellSpeed: 0.45,
      noiseScale: 1.52,
      noiseTimeScale: 0.6,
      distort: 0.35,
      flowZ: 0.08,
      edgeThreshold: 0.067,
      shoreColor: "#b8ecfa",
      midColor: "#7ed4f8",
      deepColor: "#3a6a8c",
      highlightColor: "#e8f8ff",
      depthRampShoreMid: 0.36,
      depthRampMidDeep: 0.72,
      opacity: 0.78,
      foamColor: "#e8f4ff",
      lineWidth: 0.5,
      glowWidth: 2.0,
      waterlineIntensity: 2.5,
      sinkOffset: -0.05,
      preset: "Small lake",
      style: "Ocean",
      transformMode: "translate",
      reflectionEnabled: true,
      reflectionScale: 0.5,
      reflectionEveryN: 2,
    },
    /**
     * Global map-covering LOD ocean (render/water/worldOcean.js). Distinct from
     * the placed water bodies above — this is one world-spanning sea with waves,
     * islands = terrain above seaLevel. Disabled by default.
     */
    worldOcean: {
      enabled: false,
      seaLevel: 0,
      // waves (GPU FFT)
      windSpeed: 14,
      windAngleDeg: 38,
      fftChoppiness: 1.28,
      fftSwellAmp: 1.15,
      fftRippleAmp: 0.55,
      fftUpdateHz: 30,
      // colour / depth
      shoreColor: "#8fe5d8",
      midColor: "#2ca8a8",
      deepColor: "#0b3a4a",
      highlightColor: "#a0e6e0",
      depthAbsorb: 0.14,
      opacity: 1.0,
      // reflections / fresnel
      envReflectIntensity: 1.05,
      fresnelMax: 0.72,
      // foam / whitecaps
      foamEnabled: true,
      foamColor: "#f0fbfa",
      foamIntensity: 1.25,
      whitecapEnabled: true,
      whitecapIntensity: 0.88,
      // horizon
      horizonFadeEnabled: true,
      // underwater (DOM tint overlay; toggleable, ~zero GPU cost)
      underwaterEnabled: false,
      uwEyeOffset: 0,
      uwTransitionSpeed: 5,
      uwTint: "#0a3a44",
      uwTintMax: 0.72,
      uwDepthDarken: 0.015,
      // LOD / perf
      levels: 7,
      gridM: 64,
      baseCell: 1.0,
      horizonScale: 6.0,
    },
    /** NPC / enemy spawn authoring (capsule placeholders → GLB later). */
    actors: {
      placeTool: "npc",
      transformMode: "translate",
      capsuleRadius: 0.35,
      capsuleHeight: 1.0,
      floorOffset: 0,
      npcColor: "#33aa88",
      enemyColor: "#8b2549",
      npcDefaults: {
        enabled: true,
        speed: 2.2,
        wanderRadius: 12,
        directionChangeInterval: 3,
        turnSpeed: 5,
        idleWhenNearPlayer: true,
        nearPlayerDistance: 4,
      },
      enemyDefaults: {
        enabled: true,
        maxHp: 100,
        speed: 1.8,
        wanderRadius: 8,
        directionChangeInterval: 4,
        turnSpeed: 4,
        /** Enemies keep patrolling when the player is close (unlike NPCs). */
        idleWhenNearPlayer: false,
        nearPlayerDistance: 5,
      },
      dialogue: {
        enabled: true,
        interactRadius: 3.5,
        defaultDialogueId: "villager_greet",
      },
    },
    waterfall: {
      placeTool: "waterfall",
      splashVisible: true,
      transformMode: "translate",
      width: 4,
      totalHeight: 8,
      topLength: 2.5,
      radius: 1.2,
      segments: 128,
      flowSpeed: 0.5,
      opacity: 0.92,
      colorA: "#00544c",
      colorB: "#38d0d0",
      colorC: "#c8f0ee",
      splashRadius: 3.35,
      splashCapAngle: 0.42,
      splashYOffset: 0.0,
      splashOpacity: 0.88,
      splashNoiseScale: 2.35,
      splashFlow: 1.35,
      splashDisp: 0.62,
      splashColorA: "#f8fbff",
      splashColorB: "#a8e8f5",
    },
    road: {
      width: 40,
      segments: 400,
      heightOffset: 0,
      adaptiveLift: true,
      slopeLift: 0.35,
      liftMax: 0.6,
      closed: false,
      selectedPointY: 0,
      showHandles: true,
      activeRoadIndex: 0,
      activeStyleSectionIndex: 0,
      asphaltDark: "#252528",
      asphaltLight: "#4a4a52",
      grainScale: 14,
      grainStrength: 0.38,
      lineColor: "#f2f2f2",
      lineWidth: 0.035,
      lineSoftness: 0.003,
      lineInset: 0.055,
      edgeBlendWidth: 0.0,
      edgeBlendNoise: 8.0,
      centerLine: true,
      centerLineColor: "#f0c040",
      centerLineWidth: 0.014,
      centerLineSoftness: 0.002,
      centerLineDashed: false,
      centerLineDashScale: 0.3,
      doubleCenterLine: true,
      centerLineGap: 0.012,
      centerLeftEnabled: true,
      centerLeftColor: "#f0c040",
      centerLeftDashed: false,
      centerRightEnabled: true,
      centerRightColor: "#f0c040",
      centerRightDashed: false,
      laneLines: true,
      laneLineWidth: 0.012,
      laneDashScale: 0.05,
      colorTint: "#ffffff",
      colorBrightness: 0.5,
      enhanced: false,
      normalStrength: 1.0,
      roughnessBase: 0.55,
      reflectStrength: 0.6,
      mixBlur: 0.08,
      mixStrength: 1.5,
      mixContrast: 1.0,
      normalDistort: 0.12,
      dirtAmount: 0.35,
      dirtScale: 3.0,
      dirtContrast: 0.55,
      dirtTint: "#8f8578",
      edgeDirtBoost: 0.45,
      wearAmount: 0.28,
      wearScale: 7.5,
      wearContrast: 0.5,
      wearDarken: 0.22,
      scratchAmount: 0.18,
      scratchScale: 24.0,
      scratchThinness: 0.78,
      lineScratchAmount: 1.0,
      lineScratchScale: 5.0,
      lineScratchStretch: 1.0,
      lineScratchThreshold: 0.35,
      lineScratchSoftness: 0.15,
      lineScratchWarp: 0.4,
      lineScratchDetail: 1.0,
      lineScratchEdge: 0.3,
      roughnessDirtBoost: 0.16,
      roughnessWearReduce: 0.12,
      lodNear: 30,
      lodMid: 80,
      lodFar: 200,
      texScale: 4.0,
    },
    fullRoad: {
      width: 16,
      /** Upper cap on merged-mesh subdivisions (actual count = min(this, length × meshSegmentsPerMeter)). */
      segments: 240,
      /** Full Road merged ribbon: approximate vertex rows per meter of path arc length. */
      meshSegmentsPerMeter: 1.0,
      junctionSegments: 40,
      heightOffset: 0.05,
      adaptiveLift: true,
      slopeLift: 0.35,
      liftMax: 0.6,
      selectedPointY: 0,
      showHandles: true,
      nodeSnapRadius: 4.0,
      branchSnapRadius: 6.0,
      junctionRadius: 12.0,
      asphaltDark: "#252528",
      asphaltLight: "#4a4a52",
      grainScale: 14,
      grainStrength: 0.38,
      lineColor: "#f2f2f2",
      lineWidth: 0.03,
      lineSoftness: 0.003,
      lineInset: 0.055,
      edgeBlendWidth: 0.0,
      edgeBlendNoise: 8.0,
      centerLine: true,
      centerLineColor: "#f0c040",
      centerLineWidth: 0.012,
      centerLineSoftness: 0.002,
      centerLineDashed: true,
      centerLineDashScale: 0.08,
      doubleCenterLine: false,
      centerLineGap: 0.012,
      centerLeftEnabled: true,
      centerLeftColor: "#f0c040",
      centerLeftDashed: false,
      centerRightEnabled: true,
      centerRightColor: "#f0c040",
      centerRightDashed: false,
      laneLines: false,
      laneLineWidth: 0.01,
      laneDashScale: 0.08,
      colorTint: "#ffffff",
      colorBrightness: 0.62,
      enhanced: false,
      normalStrength: 1.0,
      roughnessBase: 0.55,
      reflectStrength: 0.45,
      mixBlur: 0.08,
      mixStrength: 1.2,
      mixContrast: 1.0,
      normalDistort: 0.12,
      dirtAmount: 0.42,
      dirtScale: 3.6,
      dirtContrast: 0.6,
      dirtTint: "#8f8578",
      edgeDirtBoost: 0.65,
      wearAmount: 0.35,
      wearScale: 8.5,
      wearContrast: 0.55,
      wearDarken: 0.26,
      scratchAmount: 0.2,
      scratchScale: 26.0,
      scratchThinness: 0.8,
      lineScratchAmount: 1.0,
      lineScratchScale: 5.0,
      lineScratchStretch: 1.0,
      lineScratchThreshold: 0.35,
      lineScratchSoftness: 0.15,
      lineScratchWarp: 0.4,
      lineScratchDetail: 1.0,
      lineScratchEdge: 0.3,
      roughnessDirtBoost: 0.2,
      roughnessWearReduce: 0.14,
      wetAmount: 0.45,
      wetCoverage: 1.0,
      puddleAmount: 0.35,
      puddleScale: 2.2,
      puddleContrast: 0.6,
      puddleEdgeBoost: 0.2,
      wetDarkening: 0.18,
      wetRoughnessMin: 0.14,
      puddleReflectStrength: 0.55,
      puddleSkySuppress: 0.9,
      puddleTint: "#5b5a58",
      lodNear: 30,
      lodMid: 80,
      lodFar: 200,
      texScale: 3.0,
      // Guardrail painting
      guardrailMode: false,
      guardrailSide: "right",
      guardrailHeight: 0.5,
      guardrailDepth: 0.2,
      guardrailThickness: 0.02,
      guardrailCrownDepth: 0.05,
      guardrailPathSegments: 80,
      guardrailPostSpacing: 2.0,
      guardrailPostWidth: 0.08,
      guardrailPostDepth: 0.06,
      guardrailPostHeight: 0.6,
      guardrailRailYOffset: 0.25,
      guardrailPostSink: 0.04,
      guardrailColor: "#9aa0a8",
      guardrailEdgeOffset: 0.3,
      // Kerb painting (racing curbs)
      kerbMode: false,
      kerbSide: "right",
      kerbWidth: 0.8,
      kerbHeight: 0.12,
      kerbLipHeight: 0.03,
      kerbEdgeOffset: 0.0,
      kerbColorA: "#cc2222",
      kerbColorB: "#f2f2f2",
      kerbStripeLength: 0.8,
      // Concrete barrier painting
      barrierMode: false,
      barrierSide: "right",
      barrierHeight: 0.85,
      barrierTopWidth: 0.15,
      barrierBottomWidth: 0.45,
      barrierEdgeOffset: 0.5,
      barrierColor: "#7d7d7d",
      // Fence painting
      fenceMode: false,
      fenceSide: "right",
      fenceHeight: 1.5,
      fencePostSpacing: 2.5,
      fencePostWidth: 0.06,
      fencePostDepth: 0.04,
      fenceRailCount: 3,
      fenceRailThickness: 0.04,
      fenceEdgeOffset: 0.5,
      fenceColor: "#5a5a5a",
      // Tunnel painting (centerline accessory)
      tunnelMode: false,
      tunnelRadius: 6,
      tunnelYOffset: 0,
      tunnelRadialSegments: 20,
      tunnelPathSegments: 160,
      tunnelColor: "#6c727a",
      // Active accessory type for painting
      accessoryType: "guardrail",
      // Road decals
      decalMode: false,
      decalType: "zebraCrossing",
      decalWidth: 4.0,
      decalLength: 3.0,
      decalColor: "#ffffff",
      decalStripeCount: 8,
      decalRotation: 0,
      decalSnapToRoad: true,
      decalTransformMode: "translate",
    },
    smartRoad: {
      width: 16,
      segments: 34,
      junctionSegments: 14,
      /** When true, Smart Road surfaces use the same diffuse/ARM/normal maps as Full Road (no reflection pass). */
      usePbrTextures: false,
      profilePreset: "flat",
      profileScale: 1.0,
      heightOffset: 0.05,
      adaptiveLift: true,
      slopeLift: 0.35,
      liftMax: 0.6,
      selectedPointY: 0,
      showHandles: true,
      lanesPerDir: 1,
      twoRoadNodes: "smooth",
      endCapStyle: "flat",
      nodeSnapRadius: 4.0,
      branchSnapRadius: 6.0,
      junctionRadius: 20.0,
      asphaltDark: "#252528",
      asphaltLight: "#4a4a52",
      grainScale: 14,
      grainStrength: 0.38,
      lineColor: "#f2f2f2",
      lineWidth: 0.03,
      lineSoftness: 0.003,
      lineInset: 0.055,
      edgeBlendWidth: 0.0,
      edgeBlendNoise: 8.0,
      centerLine: true,
      centerLineColor: "#f0c040",
      centerLineWidth: 0.012,
      centerLineSoftness: 0.002,
      centerLineDashed: true,
      centerLineDashScale: 0.08,
      doubleCenterLine: false,
      centerLineGap: 0.012,
      centerLeftEnabled: true,
      centerLeftColor: "#f0c040",
      centerLeftDashed: false,
      centerRightEnabled: true,
      centerRightColor: "#f0c040",
      centerRightDashed: false,
      laneLines: false,
      laneLineWidth: 0.01,
      laneDashScale: 0.08,
      colorTint: "#ffffff",
      colorBrightness: 0.62,
      enhanced: false,
      normalStrength: 1.0,
      roughnessBase: 0.55,
      reflectStrength: 0.45,
      mixBlur: 0.08,
      mixStrength: 1.2,
      mixContrast: 1.0,
      normalDistort: 0.12,
      dirtAmount: 0.42,
      dirtScale: 3.6,
      dirtContrast: 0.6,
      dirtTint: "#8f8578",
      edgeDirtBoost: 0.65,
      wearAmount: 0.35,
      wearScale: 8.5,
      wearContrast: 0.55,
      wearDarken: 0.26,
      scratchAmount: 0.2,
      scratchScale: 26.0,
      scratchThinness: 0.8,
      lineScratchAmount: 1.0,
      lineScratchScale: 5.0,
      lineScratchStretch: 1.0,
      lineScratchThreshold: 0.35,
      lineScratchSoftness: 0.15,
      lineScratchWarp: 0.4,
      lineScratchDetail: 1.0,
      lineScratchEdge: 0.3,
      roughnessDirtBoost: 0.2,
      roughnessWearReduce: 0.14,
      wetAmount: 0.45,
      wetCoverage: 1.0,
      puddleAmount: 0.35,
      puddleScale: 2.2,
      puddleContrast: 0.6,
      puddleEdgeBoost: 0.2,
      wetDarkening: 0.18,
      wetRoughnessMin: 0.14,
      puddleReflectStrength: 0.55,
      puddleSkySuppress: 0.9,
      puddleTint: "#5b5a58",
      lodNear: 30,
      lodMid: 80,
      lodFar: 200,
      texScale: 3.0,
      guardrailMode: false,
      guardrailSide: "right",
      guardrailHeight: 0.5,
      guardrailDepth: 0.2,
      guardrailThickness: 0.02,
      guardrailCrownDepth: 0.05,
      guardrailPathSegments: 80,
      guardrailPostSpacing: 2.0,
      guardrailPostWidth: 0.08,
      guardrailPostDepth: 0.06,
      guardrailPostHeight: 0.6,
      guardrailRailYOffset: 0.25,
      guardrailPostSink: 0.04,
      guardrailColor: "#9aa0a8",
      guardrailEdgeOffset: 0.3,
      kerbMode: false,
      kerbSide: "right",
      kerbWidth: 0.8,
      kerbHeight: 0.12,
      kerbLipHeight: 0.03,
      kerbEdgeOffset: 0.0,
      kerbColorA: "#cc2222",
      kerbColorB: "#f2f2f2",
      kerbStripeLength: 0.8,
      barrierMode: false,
      barrierSide: "right",
      barrierHeight: 0.85,
      barrierTopWidth: 0.15,
      barrierBottomWidth: 0.45,
      barrierEdgeOffset: 0.5,
      barrierColor: "#7d7d7d",
      fenceMode: false,
      fenceSide: "right",
      fenceHeight: 1.5,
      fencePostSpacing: 2.5,
      fencePostWidth: 0.06,
      fencePostDepth: 0.04,
      fenceRailCount: 3,
      fenceRailThickness: 0.04,
      fenceEdgeOffset: 0.5,
      fenceColor: "#5a5a5a",
      tunnelMode: false,
      tunnelRadius: 6,
      tunnelYOffset: 0,
      tunnelRadialSegments: 20,
      tunnelPathSegments: 160,
      tunnelColor: "#6c727a",
      accessoryType: "guardrail",
      decalMode: false,
      decalType: "zebraCrossing",
      decalWidth: 4.0,
      decalLength: 3.0,
      decalColor: "#ffffff",
      decalStripeCount: 8,
      decalRotation: 0,
      decalSnapToRoad: true,
      decalTransformMode: "translate",
    },
    river: {
      width: 8,
      segments: 240,
      heightOffset: 0.12,
      selectedPointY: 0,
      showHandles: true,
      activeRiverIndex: 0,
      closed: false,
      shaderStyle: "Basic",
      shallowColor: "#5dbfaa",
      deepColor: "#1a4a6a",
      highlightColor: "#c8ecff",
      foamColor: "#ffffff",
      foamWidth: 0.18,
      opacity: 0.88,
      flowSpeed: 0.15,
    },
    /** Spline Road — a dedicated solid "depth road" mode (separate from spline).
     *  Points + sweep params; serializes the road with the project. */
    splineRoad: {
      width: 9,
      thickness: 1.0,
      bank: 0.6,
      bankSmooth: 0.12,
      segmentsPerPoint: 28,
      tension: 0.5,
      deckLift: 0.4,
      closed: false,
      showHandles: true,
      selectedPointY: 0,
      selectedPointRoll: 0,
      deckColor: "#2c3138",
      sideColor: "#6f757c",
      kerbColor: "#d23b3b",
      barrierEnabled: true,
      barrierHeight: 0.7,
      barrierDepth: 0.3,
      barrierColor: "#9aa3ad",
      snapEnabled: true, // snap an endpoint onto a nearby other endpoint (seamless join)
      points: [], // legacy single-road (migrated into roadsData on load)
      rolls: [],
      roadsData: [], // [{ points:[{x,y,z}], rolls:[num] }] — multiple road segments
    },
    spline: {
      objectType: "trees",
      spacing: 4,
      scaleMin: 1.0,
      scaleMax: 1.0,
      alignToPath: true,
      selectedPointY: 0,
      closed: false,
      showHandles: true,
      showTrain: false,
      trainSpeed: 8,
      trainScale: 1,
      plateauHeight: 24,
      plateauFalloff: 4,
      plateauHalfWidth: 10,
      tunnelRadius: 6,
      tunnelRadialSegments: 20,
      tunnelPathSegments: 220,
      tunnelColor: "#6c727a",
      /** Seal start/end for interior darkness (block outside light at that mouth). */
      tunnelCapStart: false,
      tunnelCapEnd: false,
      guardrailHeight: 2.3,
      guardrailThickness: 0.1,
      guardrailDepth: 1.1,
      guardrailCrownDepth: 0.3,
      guardrailPathSegments: 260,
      guardrailPostSpacing: 2.0,
      guardrailPostWidth: 0.32,
      guardrailPostDepth: 0.28,
      guardrailPostHeight: 2.8,
      guardrailRailYOffset: 1.15,
      guardrailPostSink: 0.16,
      guardrailColor: "#9aa0a8",
      guardrailFromRoadIndex: 0,
      guardrailFromRoadSide: "both",
      guardrailFromRoadEdgeOffset: 0.8,
      guardrailFromRoadStart: 0.0,
      guardrailFromRoadEnd: 1.0,
      guardrailFromRoadPostSpacingMul: 5.0,
      kerbWidth: 0.95,
      kerbHeight: 0.14,
      kerbLipHeight: 0.04,
      kerbTopInset: 0.0,
      kerbPathSegments: 260,
      kerbColorA: "#c92c2c",
      kerbColorB: "#f2f2f2",
      kerbStripeLength: 0.95,
      kerbSquareStripes: true,
      kerbStripeSharpness: 0.98,
      kerbNormalStrength: 0.45,
      kerbRoughnessMul: 1.0,
      kerbMetalness: 0.02,
      kerbTexUvScaleU: 1.0,
      kerbTexUvScaleV: 2.0,
      kerbTexUvOffsetU: 0.0,
      kerbTexUvOffsetV: 0.0,
      kerbTexBrightness: 0.06,
      kerbTexContrast: 1.08,
      kerbTexSaturation: 1.0,
      kerbFromRoadIndex: 0,
      kerbFromRoadSide: "both",
      kerbFromRoadEdgeOffset: -0.08,
      kerbFromRoadStart: 0.0,
      kerbFromRoadEnd: 1.0,
      kerbSplineSide: "right",
      kerbSplineLateralOffset: 0.0,
      activeKerbIndex: 0,
      kerbAutoApplyActive: true,
      /** Spline kerb mesh: `"strip"` = PBR ribbon; `"chunk"` = Smart Road / Full Road style blocks */
      kerbMeshStyle: "strip",
      splineWallHeight: 3.0,
      splineWallWidth: 0.22,
      splineWallPathSegs: 80,
      splineWallColor: "#7a7d82",
      splineFenceHeight: 1.45,
      splineFencePostSpacing: 2.1,
      splineFencePostWidth: 0.055,
      splineFencePostDepth: 0.038,
      splineFenceRailThick: 0.038,
      splineFenceColor: "#6a6d72",
      splineBarrierHeight: 0.8,
      splineBarrierDepth: 0.52,
      splineBarrierPathSegs: 72,
      splineBarrierColor: "#7d8075",
    },
    /** Revo-style fluffy tile (follows player / camera) — separate from Gemini G and billboard U. */
    revoGrass: {
      enabled: false,
      qualityPreset: "ultraCompact",
      tileSize: 60,
      bladesPerSide: 512,
      segments: 3,
      receiveShadow: false,
      bladeHeight: 1.75,
      bladeWidth: 0.06,
      bladeMinScale: 0.75,
      bladeMaxScale: 2.0,
      clumpStrength: 0,
      clumpScale: 2.0,
      baseColor: "#8c6b30",
      tipColor: "#77be13",
      colorMixFactor: 0.8,
      colorVariationStrength: 2.75,
      aoScale: 0.5,
      aoRimSmoothness: 5,
      aoRadius: 25,
      baseWindShade: 0.75,
      baseShadeHeight: 1,
      baseBending: 2,
      windStrength: 0.4,
      windSpeed: 0.25,
      windAngle: 0,
      uvWindScale: 1.75,
      trailGrowthRate: 0.04,
      trailMinScale: 0.25,
      trailRadius: 1,
      trailCrushSpeed: 0.4,
      playerRadius: 0.5,
      stochasticR0: 10,
      stochasticR1: 30,
      stochasticPMin: 0.1,
      windIntensity: 1,
      windColorStrength: 0.6,
      cullPadNdcX: 0.075,
      cullPadNdcYNear: 0.75,
      cullPadNdcYFar: 0.2,
      frustumCullEnabled: true,
      bakedShadowWeight: 1,
      playerShadowEnabled: true,
      exclusionEnabled: false,
      exclusionSource: "mask",
      exclusionThreshold: 0.25,
      computeMinIntervalMs: 33,
      useGlobalWindInPlay: true,
      colorBrightness: 1,
    },
    revoGrassPaint: {
      erase: false,
    },
    /**
     * Snow tile — moving-window grid following player/camera.
     * Surface = Snow010A PBR (color/rough/normal/AO/displacement) sampled
     * tiled by world XZ. Vertex Y = terrainY + accumulation + fine PBR
     * displacement − scrolling trail-map groove. Painted mask = artist input.
     */
    snow: {
      enabled: false,
      qualityPreset: "high",
      subdivisions: 256,
      tileSize: 110,
      /** Accumulation. */
      baseDepth: 0.1,
      altitudeY0: 30,
      altitudeY1: 200,
      altitudeDepth: 0.6,
      accumMaskEnabled: true,
      paintedAccumStrength: 1.2,
      /** Surface PBR (Snow010A). */
      tileFreq: 0.18,
      dispStrength: 0.06,
      snowColorMul: 1.0,
      colorBrightness: 1.0,
      normalScale: 0.7,
      /** Detail mapping (sample at two scales to break the obvious tile). */
      detailFreqRatio: 0.18,
      detailMix: 0.45,
      /** Rim ridges (positive Y push along the sides of wheel ruts). */
      rimRidgeScale: 0.35,
      rimSampleOffset: 0.5,
      /** Trail map (wheel ruts). */
      trailWorldSize: 200,
      trailScrollThreshold: 0.38,
      trailGrooveScale: 1.5,
      trailAlbedoCavity: 0.45,
      trailRoughnessBoost: 0.55,
      trailAoInGroove: 0.8,
      trailStampStep: 0.15,
      /** Additive heal rate per frame in normalised [0,1] units. 0 = trails permanent within the trail window. */
      trailRegrowPerFrame: 0,
      /** Wheel + chassis carving (play mode only). */
      wheelEnabled: true,
      wheelDepth: 0.5,
      wheelRadius: 0.4,
      wheelPushScale: 0.6,
      chassisStampEnabled: false,
      chassisDepth: 0.2,
      chassisRadius: 1.2,
      chassisPushScale: 0.35,
      /**
       * Slope rejection — no snow on steep terrain (matches auto-cliff so
       * snow fades out exactly where rock exposes). Uses the same
       * 4-neighbour heightmap flatness as `chunkTerrainAutoCliff.js`.
       * `slopeLinkToCliff` mirrors `autoCliff.slopeStart/slopeEnd` live.
       */
      slopeRejectEnabled: true,
      slopeLinkToCliff: true,
      slopeMin: 0.6,
      slopeMax: 0.7,
      slopeSoftness: 1.0,
      slopeAffectsTrail: true,
      /** Alpha edge fade. */
      fadeEdgeLow: 0.02,
      fadeEdgeHigh: 0.25,
      normalNeighbourShift: 0.35,
      /** Glitter sparkle (cheap pow on the displacement-tex value). */
      glitterIntensity: 1.6,
      glitterScarcity: 280,
      glitterFreq: 1.3,
    },
    snowPaint: {
      erase: false,
    },
    grass: {
      enabled: false,
      bladeHeight: 1.0,
      bladeWidth: 0.15,
      tipTaperStart: 0.5,
      bladeYSegments: 7,
      grassCount: 1516,
      fieldSize: 10,
      grassDensity: 1.0,
      windSpeed: 0.2,
      windStrength: 1.4,
      maxAngle: 1.4,
      naturalLean: 0.9,
      windAngle: 0,
      windWaveScale: 0.12,
      windGust: 0.3,
      bendFocus: 0.5,
      stiffness: 0.0,
      clumpScale: 1.5,
      clumpStrength: 0.7,
      crossed: true,
      bladeColor: "#2f6b1a", // grass-lab calibrated (was #0e300e — too dark, gradient barely read)
      tipColor: "#8cc63f", //  grass-lab calibrated (was #004d05)
      skyBlend: 0.8,
      cylindrical: 0.3,
      viewThicken: 0.45,
      aoBase: 0.25,
      aoPower: 2.0,
      colorVariation: false,
      cvHueSpread: 0.08,
      cvSatSpread: 0.3,
      cvDryAmount: 0.15,
      cvDryColor: "#8a7a3a",
      bssIntensity: 1.2,
      bssPower: 2.0,
      bssColor: "#2d7a2d",
      frontScatter: 0.3,
      rimSSS: 0.25,
      specV1Enabled: false,
      specV1Intensity: 1.5,
      specV1Color: "#ffffff",
      specV1DirX: -1.0,
      specV1DirY: 1.0,
      specV1DirZ: 0.5,
      specV1Power: 25.6,
      specV2Enabled: false,
      specV2Intensity: 1.0,
      specV2Color: "#ffffff",
      specV2DirX: -1.0,
      specV2DirY: 0.45,
      specV2DirZ: 1.0,
      specV2NoiseScale: 3.0,
      specV2NoiseStr: 0.6,
      specV2Power: 12.0,
      specV2TipBias: 0.5,
      lodEnabled: true,
      lodMidDistance: 40,
      lodFarDistance: 80,
      lodMaxDistance: 200,
      lodFadeStart: 0.75,
      lodMidPatchSize: 18,
      lodMidSegments: 3,
      lodMidGrassCount: 1500,
      lodFarPatchSize: 28,
      lodFarSegments: 1,
      lodFarGrassCount: 1300,
      lodFarBladeWidth: 0.45,
      lodMegaMaxDistance: 400,
      lodMegaPatchSize: 60,
      lodMegaSegments: 1,
      lodMegaGrassCount: 400,
      lodMegaBladeWidth: 0.7,
      lodDebug: false,
      interactionRadius: 1.5,
      interactionStrength: 0.7,
      // Renderer backend: "gemini" = patch meshes (default), "hybrid" =
      // GPU-driven compute+indirect rings (proven in grass-lab.html, ~3× GPU)
      renderMode: "gemini",
      interactionMode: 0, // hybrid only: 0 = agitation, 1 = radial parting
      receiveShadow: true,
      terrainTintEnabled: false,
      terrainTintStrength: 0.5,
      terrainTintAutoSource: true,
      terrainTintManualMode: 1,
      terrainTintRootBias: 0.35,
      slopeEnabled: true,
      slopeMin: 0.65,
      slopeMax: 0.85,
    },
    /** Decals mode (D) — textured quads; instanced per texture+opacity. */
    decal: {
      opacity: 1,
      heightOffset: 0.05,
      defaultScale: 4,
      alignToNormal: true,
      conformSubdiv: 32,
      transformMode: "translate",
    },
  };
}

export function createPerfState() {
  return {
    fps: 0,
    frameMs: 0,
    lastFrameStamp: performance.now(),
    frameAccumMs: 0,
    frameCount: 0,
    activeChunks: 0,
    stream: {
      created: 0,
      remeshed: 0,
      unloaded: 0,
    },
    queues: {
      create: 0,
      remesh: 0,
      unload: 0,
    },
    trisApprox: 0,
  };
}

export function tickPerf(perf, nowMs, frameMs) {
  perf.frameMs = frameMs;
  perf.frameAccumMs += frameMs;
  perf.frameCount++;
  const elapsed = nowMs - perf.lastFrameStamp;
  if (elapsed >= 500) {
    perf.fps = (perf.frameCount * 1000) / elapsed;
    perf.frameCount = 0;
    perf.frameAccumMs = 0;
    perf.lastFrameStamp = nowMs;
  }
}
