/**
 * Procedural object registry — single source of truth shared by the lab
 * (template-unreal-objects.html) and the game engine.
 *
 * Each descriptor is self-describing:
 *   id, label            — identity + UI name
 *   build(opts)          — ({points, closed, params, getWorldHeight}) => THREE.Group|null
 *   defaults             — default params object
 *   minPoints            — spline points required (1 = point object, 2 = span/path)
 *   preview              — gallery preview: "point" | "strip"
 *   hero                 — hero/studio spline points
 *   schema               — declarative param list (drives the inspector UI AND
 *                          serves as engine-side metadata for props/serialize)
 *   initParams?          — extra non-schema params merged into defaults
 *   resolveParams?(p)    — map editor params → build params (e.g. _map → map)
 *
 * Schema entry types: slider | color | toggle | select | file | sep
 * The engine can ignore the UI-only bits and just read build/defaults/schema.
 */

import { buildGuardrailMesh, GUARDRAIL_DEFAULTS, HERO_STRIP_POINTS } from "./guardrail.js";
import { buildFenceMesh, FENCE_DEFAULTS } from "./fence.js";
import { buildBarrierMesh, BARRIER_DEFAULTS } from "./barrier.js";
import { buildKerbMesh, KERB_DEFAULTS } from "./kerb.js";
import { buildWoodFenceMesh, WOOD_FENCE_DEFAULTS } from "./woodFence.js";
import { buildWoodPlankFenceMesh, WOOD_PLANK_FENCE_DEFAULTS } from "./woodPlankFence.js";
import { buildStreetLampMesh, STREET_LAMP_DEFAULTS, STREET_LAMP_HERO_POINTS } from "./streetLamp.js";
import { buildSidewalkMesh, SIDEWALK_DEFAULTS } from "./sidewalk.js";
import { buildWindmillMesh, WINDMILL_DEFAULTS, WINDMILL_HERO_POINTS } from "./windmill.js";
import { buildTrafficLightMesh, TRAFFIC_LIGHT_DEFAULTS, TRAFFIC_LIGHT_HERO_POINTS } from "./trafficLight.js";
import { buildBridgeMesh, BRIDGE_DEFAULTS, BRIDGE_HERO_POINTS } from "./bridge.js";
import { buildGantryMesh, GANTRY_DEFAULTS, GANTRY_HERO_POINTS } from "./gantry.js";
import { buildPowerLineMesh, POWER_LINE_DEFAULTS, POWER_LINE_HERO_POINTS } from "./powerLine.js";
import { buildBillboardMesh, BILLBOARD_DEFAULTS, BILLBOARD_HERO_POINTS } from "./billboard.js";
import { buildTireWallMesh, TIRE_WALL_DEFAULTS, TIRE_WALL_HERO_POINTS } from "./tireWall.js";
import { buildFloodlightMesh, FLOODLIGHT_DEFAULTS, FLOODLIGHT_HERO_POINTS } from "./floodlight.js";

// schema helpers (compact)
const sl = (key, label, min, max, step) => ({ type: "slider", key, label, min, max, step });
const co = (key, label) => ({ type: "color", key, label });
const tg = (key, label) => ({ type: "toggle", key, label });
const se = (key, label, options) => ({ type: "select", key, label, options });
const fi = (key, label) => ({ type: "file", key, label, accept: "image/*" });
const SEP = { type: "sep" };
const SIDE = { right: "Right", left: "Left" };

export const OBJECTS = [
  {
    id: "guardrail", label: "Guardrail",
    build: buildGuardrailMesh, defaults: GUARDRAIL_DEFAULTS,
    minPoints: 2, preview: "strip", hero: HERO_STRIP_POINTS,
    schema: [
      sl("height", "Height", 0.1, 3, 0.01),
      sl("depth", "Depth", 0.05, 2, 0.01),
      sl("crownDepth", "Crown", 0, 0.5, 0.005),
      sl("thickness", "Thickness", 0, 0.2, 0.002),
      sl("railYOffset", "Rail Y", 0, 2, 0.01),
      SEP,
      sl("postSpacing", "Post gap", 0.5, 8, 0.1),
      sl("postWidth", "Post W", 0.02, 0.6, 0.01),
      sl("postDepth", "Post D", 0.02, 0.6, 0.01),
      sl("postHeight", "Post H", 0.2, 3, 0.05),
      sl("postSink", "Post sink", 0, 0.5, 0.01),
      SEP,
      sl("pathSegments", "Path segs", 16, 320, 1),
      co("color", "Color"),
      sl("roughness", "Roughness", 0, 1, 0.01),
      sl("metalness", "Metalness", 0, 1, 0.01),
    ],
  },
  {
    id: "fence", label: "Fence",
    build: buildFenceMesh, defaults: FENCE_DEFAULTS,
    minPoints: 2, preview: "strip", hero: HERO_STRIP_POINTS,
    schema: [
      sl("height", "Height", 0.35, 4, 0.05),
      sl("postSpacing", "Post gap", 0.4, 8, 0.1),
      sl("postWidth", "Post W", 0.02, 0.3, 0.01),
      sl("postDepth", "Post D", 0.02, 0.3, 0.01),
      sl("railCount", "Rail count", 1, 6, 1),
      sl("railThickness", "Rail thick", 0.01, 0.15, 0.005),
      sl("pathSegments", "Path segs", 16, 320, 1),
      co("color", "Color"),
      sl("roughness", "Roughness", 0, 1, 0.01),
      sl("metalness", "Metalness", 0, 1, 0.01),
    ],
  },
  {
    id: "barrier", label: "Barrier",
    build: buildBarrierMesh, defaults: BARRIER_DEFAULTS,
    minPoints: 2, preview: "strip", hero: HERO_STRIP_POINTS,
    schema: [
      sl("height", "Height", 0.2, 2, 0.01),
      sl("topWidth", "Top W", 0.05, 0.8, 0.01),
      sl("bottomWidth", "Bottom W", 0.1, 1.2, 0.01),
      sl("pathSegments", "Path segs", 16, 320, 1),
      co("color", "Color"),
      sl("roughness", "Roughness", 0, 1, 0.01),
      sl("metalness", "Metalness", 0, 1, 0.01),
    ],
  },
  {
    id: "kerb", label: "Kerb",
    build: buildKerbMesh, defaults: KERB_DEFAULTS,
    minPoints: 2, preview: "strip", hero: HERO_STRIP_POINTS,
    schema: [
      se("side", "Side", SIDE),
      sl("width", "Width", 0.2, 2, 0.01),
      sl("height", "Height", 0.02, 0.5, 0.005),
      sl("lipHeight", "Lip H", 0, 0.15, 0.005),
      sl("stripeLength", "Stripe len", 0.2, 3, 0.05),
      co("colorA", "Color A"),
      co("colorB", "Color B"),
      sl("roughness", "Roughness", 0, 1, 0.01),
      sl("metalness", "Metalness", 0, 1, 0.01),
    ],
  },
  {
    id: "woodFence", label: "Wood picket",
    build: buildWoodFenceMesh, defaults: WOOD_FENCE_DEFAULTS,
    minPoints: 2, preview: "strip", hero: HERO_STRIP_POINTS,
    schema: [
      sl("height", "Height", 0.4, 3, 0.05),
      sl("postSpacing", "Post gap", 0.8, 6, 0.1),
      sl("postWidth", "Post W", 0.06, 0.35, 0.01),
      sl("postDepth", "Post D", 0.05, 0.3, 0.01),
      SEP,
      sl("picketWidth", "Board W", 0.04, 0.25, 0.005),
      sl("picketDepth", "Board D", 0.02, 0.12, 0.005),
      sl("picketGap", "Board gap", 0, 0.15, 0.005),
      sl("railCount", "Rail count", 0, 3, 1),
      sl("railThickness", "Rail thick", 0.03, 0.14, 0.005),
      SEP,
      sl("leanAmount", "Lean °", 0, 25, 0.5),
      sl("leanRatio", "Lean ratio", 0, 1, 0.01),
      sl("heightVariation", "H var", 0, 0.25, 0.01),
      sl("colorVariation", "Color var", 0, 1, 0.01),
      sl("seed", "Seed", 0, 9999, 1),
      SEP,
      co("colorMain", "Wood A"),
      co("colorAlt", "Wood B"),
      sl("roughness", "Roughness", 0, 1, 0.01),
      tg("flatShading", "Flat shade"),
    ],
  },
  {
    id: "woodPlankFence", label: "Wood plank",
    build: buildWoodPlankFenceMesh, defaults: WOOD_PLANK_FENCE_DEFAULTS,
    minPoints: 2, preview: "strip", hero: HERO_STRIP_POINTS,
    schema: [
      sl("height", "Height", 0.5, 3, 0.05),
      sl("postSpacing", "Post gap", 1, 6, 0.1),
      sl("postWidth", "Post W", 0.08, 0.35, 0.01),
      sl("postDepth", "Post D", 0.07, 0.3, 0.01),
      sl("postOverhang", "Post top+", 0, 0.5, 0.01),
      SEP,
      sl("railCount", "Rail count", 1, 4, 1),
      sl("railThickness", "Rail thick", 0.04, 0.2, 0.005),
      sl("railDepth", "Rail depth", 0.03, 0.16, 0.005),
      sl("railInset", "Rail inset", 0, 0.12, 0.005),
      SEP,
      sl("leanAmount", "Rail slant", 0, 0.6, 0.01),
      sl("leanRatio", "Slant ratio", 0, 1, 0.01),
      sl("railYOffset", "Rail jitter", 0, 0.12, 0.005),
      sl("colorVariation", "Color var", 0, 1, 0.01),
      sl("seed", "Seed", 0, 9999, 1),
      SEP,
      co("colorMain", "Wood A"),
      co("colorAlt", "Wood B"),
      sl("roughness", "Roughness", 0, 1, 0.01),
      tg("flatShading", "Flat shade"),
    ],
  },
  {
    id: "streetLamp", label: "Street lamp",
    build: buildStreetLampMesh, defaults: STREET_LAMP_DEFAULTS,
    minPoints: 1, preview: "point", hero: STREET_LAMP_HERO_POINTS,
    schema: [
      sl("spacing", "Spacing", 4, 40, 0.5),
      sl("sideOffset", "Side offset", 0, 8, 0.1),
      se("side", "Side", SIDE),
      SEP,
      sl("poleHeight", "Pole H", 2, 8, 0.05),
      sl("poleRadiusBase", "Pole base R", 0.04, 0.25, 0.005),
      sl("poleRadiusTop", "Pole top R", 0.03, 0.2, 0.005),
      sl("baseWidth", "Base W", 0.2, 1, 0.02),
      sl("baseHeight", "Base H", 0.04, 0.4, 0.01),
      sl("collarScale", "Collar scale", 1, 2.2, 0.05),
      SEP,
      sl("armLength", "Arm len", 0.3, 2.5, 0.05),
      sl("armMountHeight", "Arm height", 1.5, 7, 0.05),
      sl("armThickness", "Arm thick", 0.04, 0.18, 0.005),
      sl("armPitch", "Arm pitch°", -35, 20, 1),
      SEP,
      sl("headWidth", "Head W", 0.2, 1.2, 0.02),
      sl("headHeight", "Head H", 0.12, 0.8, 0.02),
      sl("headDepth", "Head D", 0.15, 0.9, 0.02),
      sl("headDrop", "Head drop", 0, 0.35, 0.01),
      sl("capHeight", "Cap H", 0, 0.35, 0.01),
      sl("bulbSize", "Bulb size", 0.08, 0.5, 0.01),
      SEP,
      co("emissiveColor", "Glow color"),
      sl("emissiveIntensity", "Glow int", 0, 6, 0.1),
      tg("castLight", "Point light"),
      sl("lightIntensity", "Light int", 0, 4, 0.05),
      sl("lightDistance", "Light dist", 4, 40, 1),
      SEP,
      co("colorPole", "Pole color"),
      co("colorMetal", "Metal color"),
      sl("roughness", "Roughness", 0, 1, 0.01),
      sl("metalness", "Metalness", 0, 1, 0.01),
      sl("leanAmount", "Lean °", 0, 8, 0.25),
      sl("leanRatio", "Lean ratio", 0, 1, 0.01),
      sl("seed", "Seed", 0, 9999, 1),
      tg("flatShading", "Flat shade"),
    ],
  },
  {
    id: "sidewalk", label: "Sidewalk",
    build: buildSidewalkMesh, defaults: SIDEWALK_DEFAULTS,
    minPoints: 2, preview: "strip", hero: HERO_STRIP_POINTS,
    initParams: { _map: null },
    resolveParams: (p) => ({ ...p, map: p._map ?? null }),
    schema: [
      se("side", "Side", SIDE),
      sl("sideOffset", "Side offset", 0, 12, 0.1),
      sl("width", "Width", 1, 12, 0.1),
      sl("thickness", "Thickness", 0.02, 0.5, 0.01),
      sl("yOffset", "Y offset", 0, 0.2, 0.002),
      sl("pathSegments", "Path segs", 16, 320, 1),
      SEP,
      sl("uvRepeatAlong", "UV along (m)", 0.5, 10, 0.1),
      sl("uvRepeatAcross", "UV across (m)", 0.5, 10, 0.1),
      co("color", "Color"),
      sl("roughness", "Roughness", 0, 1, 0.01),
      sl("metalness", "Metalness", 0, 1, 0.01),
      SEP,
      fi("_map", "Texture"),
    ],
  },
  {
    id: "windmill", label: "Windmill",
    build: buildWindmillMesh, defaults: WINDMILL_DEFAULTS,
    minPoints: 1, preview: "point", hero: WINDMILL_HERO_POINTS,
    schema: [
      sl("spacing", "Spacing", 12, 200, 1),
      sl("sideOffset", "Side offset", 0, 40, 0.5),
      se("side", "Side", SIDE),
      sl("scale", "Scale", 0.1, 3, 0.05),
      sl("rotorSpeedDeg", "Rotor °/s", 0, 120, 1),
      se("rotorAxis", "Rotor axis", { x: "X", y: "Y", z: "Z" }),
      tg("facePath", "Face path"),
    ],
  },
  {
    id: "trafficLight", label: "Traffic Light",
    build: buildTrafficLightMesh, defaults: TRAFFIC_LIGHT_DEFAULTS,
    minPoints: 1, preview: "point", hero: TRAFFIC_LIGHT_HERO_POINTS,
    schema: [
      sl("poleHeight", "Pole H (place height)", 0.5, 8, 0.05),
      sl("poleRadius", "Pole R", 0.04, 0.2, 0.005),
      SEP,
      sl("lampSize", "Lamp size", 0.15, 0.8, 0.01),
      sl("lampGap", "Lamp gap", 0.2, 1.0, 0.01),
      SEP,
      sl("density", "LED density", 6, 32, 1),
      sl("dotRadius", "Dot size", 0.12, 0.5, 0.01),
      sl("emissive", "Brightness", 1, 14, 0.1),
      SEP,
      sl("greenDur", "Green s", 0, 10, 0.1),
      sl("amberDur", "Amber s", 0, 6, 0.1),
      sl("redDur", "Red s", 0, 10, 0.1),
      sl("redAmberDur", "Red+Amber s", 0, 6, 0.1),
      sl("speed", "Speed", 0.1, 5, 0.1),
      SEP,
      co("redColor", "Red"),
      co("amberColor", "Amber"),
      co("greenColor", "Green"),
    ],
  },
  {
    id: "bridge", label: "Bridge",
    build: buildBridgeMesh, defaults: BRIDGE_DEFAULTS,
    minPoints: 2, preview: "strip", hero: BRIDGE_HERO_POINTS,
    schema: [
      sl("width", "Width", 1, 8, 0.1),
      sl("archHeight", "Arch height", 0, 4, 0.05),
      sl("deckClearance", "Deck lift", 0, 1.5, 0.02),
      sl("pathSegments", "Resolution", 20, 120, 2),
      SEP,
      sl("plankWidth", "Plank width", 0.15, 0.7, 0.01),
      sl("plankGap", "Plank gap", 0, 0.15, 0.005),
      sl("deckThickness", "Deck thick", 0.05, 0.3, 0.01),
      sl("plankToneVar", "Tone var", 0, 0.3, 0.01),
      SEP,
      sl("railHeight", "Rail height", 0.4, 1.6, 0.02),
      sl("postSpacing", "Post spacing", 0.8, 6, 0.1),
      tg("midRail", "Mid rail"),
      SEP,
      tg("truss", "Arched truss"),
      sl("trussCross", "Truss cross-beams", 0, 14, 1),
      tg("abutments", "Stone abutments"),
      SEP,
      tg("lanterns", "Lanterns (glow)"),
      sl("lanternSpacing", "Lantern spacing", 2, 16, 0.5),
      sl("lanternIntensity", "Lantern glow", 0, 12, 0.2),
      co("lanternColor", "Lantern"),
      SEP,
      co("woodMain", "Deck wood"),
      co("woodAlt", "Structure"),
      co("woodRail", "Railing"),
      co("stoneColor", "Stone"),
    ],
  },
  {
    id: "gantry", label: "Gantry",
    build: buildGantryMesh, defaults: GANTRY_DEFAULTS,
    minPoints: 2, preview: "strip", hero: GANTRY_HERO_POINTS,
    schema: [
      se("boardMode", "Board", { checker: "Checkered", chevron: "Chevron", lights: "Start lights" }),
      se("boardShape", "Pixel style", { round: "Round dots", square: "Square dots", diamond: "Diamond", solid: "Solid (no dots)" }),
      sl("towerHeight", "Clearance H", 2, 12, 0.1),
      sl("beamHeight", "Beam height", 0.4, 2.5, 0.05),
      sl("beamDepth", "Beam depth", 0.3, 1.5, 0.05),
      sl("towerWidth", "Tower W", 0.2, 1.2, 0.02),
      sl("strutSpacing", "Strut spacing", 0.5, 4, 0.1),
      SEP,
      sl("boardHeightFrac", "Board H frac", 0.3, 1, 0.02),
      sl("boardInsetEnds", "Board inset", 0, 3, 0.05),
      sl("dotPitch", "LED pitch (m)", 0.04, 0.3, 0.005),
      sl("dotRadius", "Dot size", 0.12, 0.5, 0.01),
      sl("emissive", "Brightness", 1, 14, 0.1),
      SEP,
      sl("checkerSize", "Checker size (m)", 0.15, 2, 0.05),
      sl("chevronSpacing", "Chevron spacing (m)", 0.3, 4, 0.05),
      sl("panSpeed", "Chevron speed", -1.5, 1.5, 0.01),
      co("chevronColor", "Chevron"),
      co("lightColor", "Start light"),
      SEP,
      tg("cornerLights", "Corner lights"),
      co("cornerColor", "Corner"),
      co("colorTower", "Tower"),
      co("colorBeam", "Beam"),
    ],
  },
  {
    id: "powerLine", label: "Power line",
    build: buildPowerLineMesh, defaults: POWER_LINE_DEFAULTS,
    minPoints: 2, preview: "strip", hero: POWER_LINE_HERO_POINTS,
    schema: [
      sl("spacing", "Pole spacing", 5, 40, 0.5),
      sl("poleHeight", "Pole height", 3, 14, 0.1),
      sl("poleRadius", "Pole radius", 0.06, 0.4, 0.01),
      SEP,
      sl("crossarms", "Crossarms", 1, 4, 1),
      sl("crossarmLength", "Arm length", 1, 4, 0.1),
      sl("crossarmDrop", "Arm drop", 0, 2, 0.05),
      sl("crossarmSpacing", "Arm spacing", 0.3, 2, 0.05),
      tg("insulators", "Insulators"),
      tg("topWire", "Top earth wire"),
      SEP,
      sl("wireSag", "Wire sag", 0, 4, 0.05),
      sl("wireRadius", "Wire radius", 0.01, 0.12, 0.005),
      sl("wireSegments", "Wire segments", 4, 30, 1),
      SEP,
      co("poleColor", "Pole"),
      co("armColor", "Arm"),
      co("wireColor", "Wire"),
      co("insulatorColor", "Insulator"),
    ],
  },
  {
    id: "billboard", label: "Billboard",
    build: buildBillboardMesh, defaults: BILLBOARD_DEFAULTS,
    minPoints: 2, preview: "strip", hero: BILLBOARD_HERO_POINTS,
    schema: [
      se("surface", "Surface", { led: "LED board", matte: "Matte print" }),
      se("boardMode", "Board", { checker: "Checkered", chevron: "Chevron", lights: "Lights" }),
      se("boardShape", "Pixel style", { round: "Round", square: "Square", diamond: "Diamond", solid: "Solid" }),
      SEP,
      sl("spacing", "Spacing", 6, 60, 0.5),
      sl("sideOffset", "Side offset", 0, 20, 0.2),
      se("side", "Side", SIDE),
      sl("tiltDeg", "Tilt °", 0, 25, 0.5),
      SEP,
      sl("panelWidth", "Panel W", 2, 12, 0.1),
      sl("panelHeight", "Panel H", 1, 6, 0.1),
      sl("panelBottom", "Mount height", 0.2, 4, 0.05),
      sl("frameThick", "Frame", 0.04, 0.4, 0.01),
      SEP,
      sl("dotPitch", "LED pitch (m)", 0.03, 0.25, 0.005),
      sl("dotRadius", "Dot size", 0.12, 0.5, 0.01),
      sl("emissive", "Brightness", 1, 12, 0.1),
      sl("checkerSize", "Checker (m)", 0.1, 1.5, 0.05),
      sl("chevronSpacing", "Chevron (m)", 0.3, 3, 0.05),
      sl("panSpeed", "Speed", -1.5, 1.5, 0.01),
      SEP,
      co("chevronColor", "Chevron"),
      co("boardColorA", "Checker A"),
      co("boardColorB", "Checker B"),
      co("matteColor", "Matte"),
      co("colorFrame", "Frame col"),
    ],
  },
  {
    id: "tireWall", label: "Tire wall",
    build: buildTireWallMesh, defaults: TIRE_WALL_DEFAULTS,
    minPoints: 2, preview: "strip", hero: TIRE_WALL_HERO_POINTS,
    schema: [
      sl("outerRadius", "Tyre radius", 0.2, 0.7, 0.01),
      sl("tube", "Rubber thick", 0.05, 0.3, 0.005),
      sl("rows", "Rows (height)", 1, 8, 1),
      sl("depth", "Depth (rows)", 1, 4, 1),
      sl("sideOffset", "Side offset", -8, 8, 0.1),
      se("side", "Side", SIDE),
      SEP,
      tg("brickOffset", "Brick offset"),
      sl("jitter", "Jitter", 0, 0.15, 0.005),
      sl("rotJitter", "Spin var", 0, 1.5, 0.05),
      tg("topRail", "Top binding rail"),
      SEP,
      co("tireColor", "Tyre"),
      co("railColor", "Rail"),
      sl("toneVar", "Tone var", 0, 0.3, 0.01),
      sl("roughness", "Roughness", 0, 1, 0.01),
    ],
  },
  {
    id: "floodlight", label: "Floodlight",
    build: buildFloodlightMesh, defaults: FLOODLIGHT_DEFAULTS,
    minPoints: 1, preview: "point", hero: FLOODLIGHT_HERO_POINTS,
    schema: [
      sl("spacing", "Spacing", 10, 120, 1),
      sl("sideOffset", "Side offset", 0, 40, 0.5),
      se("side", "Side", SIDE),
      SEP,
      sl("mastHeight", "Mast height", 4, 28, 0.5),
      sl("mastRadiusBase", "Mast base R", 0.15, 0.6, 0.01),
      sl("mastRadiusTop", "Mast top R", 0.08, 0.4, 0.01),
      SEP,
      sl("headTiltDeg", "Head tilt °", 0, 60, 1),
      sl("lampCols", "Lamp cols", 1, 8, 1),
      sl("lampRows", "Lamp rows", 1, 6, 1),
      sl("lampW", "Lamp W", 0.3, 1.2, 0.02),
      sl("lampH", "Lamp H", 0.2, 1.0, 0.02),
      sl("emissive", "Brightness", 1, 16, 0.1),
      co("lampColor", "Lamp"),
      SEP,
      tg("castLight", "Cast real light"),
      sl("lightIntensity", "Light int", 0, 8, 0.1),
      sl("lightDistance", "Light dist", 20, 160, 5),
      SEP,
      co("colorMast", "Mast"),
      co("colorHousing", "Housing"),
    ],
  },
];

export const OBJECT_MAP = new Map(OBJECTS.map((o) => [o.id, o]));
