// THE AURÈS MAP'S TRACKS — GENERATED by tools/algTracks.mjs --route; do not
// edit by hand (change the ROUTES there and re-route). World metres, [x, z]
// control points of a Catmull-Rom line (resample to walk it).
//
// kind "piste": the dirt vehicle track (the post, the oasis, the villages);
// "mule": a foot path (the dechra, the gully mouths, up to the katiba). The
// game reads these for patrols, convoys, ambushes and mines; the map tool
// paints and ruts the same lines.
export const TRACKS = [
  {
    "name": "Piste de Ouled Ali",
    "kind": "piste",
    "from": "gate",
    "to": "Mechta Ouled Ali",
    "length": 153,
    "points": [
      [110.3, 218.3], [119, 216], [121, 212], [127, 172], [153, 158], [163, 148],
      [169, 138], [171, 134], [173, 130], [169, 116], [161, 100],
    ]
  },
  {
    "name": "Piste de l'Oued",
    "kind": "piste",
    "from": "Mechta Ouled Ali",
    "to": "Mechta el Oued",
    "length": 105,
    "points": [
      [181, 32], [199, 24], [201, 6], [213, 0], [247, -40],
    ]
  },
  {
    "name": "Piste de la dechra",
    "kind": "piste",
    "from": "network",
    "to": "Dechra Tighanimine",
    "length": 344,
    "points": [
      [125, 178], [11, 178], [-1, 172], [-45, 176], [-115, 132], [-129, 136],
      [-133, 136], [-135, 136], [-139, 134], [-167, 148], [-191, 146],
    ]
  },
  {
    "name": "Sentier de la koubba",
    "kind": "mule",
    "from": "Dechra Tighanimine",
    "to": "Sidi Ahmed",
    "length": 24,
    "points": [
      [-255, 118], [-265, 96],
    ]
  },
  {
    "name": "Sentier du ravin ouest",
    "kind": "mule",
    "from": "Dechra Tighanimine",
    "to": "Gully mouth west",
    "length": 113,
    "points": [
      [-235, 102], [-229, 88], [-271, 4],
    ]
  },
  {
    "name": "Sentier de la katiba ouest",
    "kind": "mule",
    "from": "Gully mouth west",
    "to": "Katiba camp",
    "length": 279,
    "points": [
      [-271, 4], [-261, 24], [-221, 14], [-169, 14], [-155, -2], [-163, -22],
      [-161, -42], [-187, -94], [-199, -130],
    ]
  },
  {
    "name": "Sentier du ravin est",
    "kind": "mule",
    "from": "Mechta Ouled Ali",
    "to": "Gully mouth east",
    "length": 242,
    "points": [
      [111, 46], [67, 26], [55, 14], [29, 0], [13, -26], [13, -28],
      [17, -30], [15, -34], [-7, -34], [-29, -46], [-51, -68], [-73, -76],
    ]
  },
  {
    "name": "Sentier de la katiba est",
    "kind": "mule",
    "from": "Gully mouth east",
    "to": "Katiba camp",
    "length": 139,
    "points": [
      [-83, -88], [-93, -114], [-109, -128], [-123, -156], [-145, -178], [-149, -180],
      [-159, -174], [-169, -172],
    ]
  },
  {
    "name": "Piste du ksar",
    "kind": "piste",
    "from": "network",
    "to": "Ksar el Hamra",
    "length": 253,
    "points": [
      [181, 32], [175, 26], [163, 20], [139, 20], [129, 24], [123, 30],
      [115, 38], [89, 38], [55, 14], [45, 8], [37, 6], [33, 2],
      [29, 0], [23, -6], [17, -14], [13, -24], [13, -26], [17, -28],
      [21, -30], [15, -34], [11, -34], [-3, -42], [-7, -50],
    ]
  }
];
